# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rymndhng
tagline:          '(repeatedly #(do (coffee) (think) (write)))'
description:      'Blog about Software Engineering and etc. Opinions are my own.'
url:              https://rymndhng.github.io

author:
  name:           'Raymond Huang'
  url:            https://rymndhng.github.io
  email:          rymndhng+iterate@gmail.com

paginate:         5

plugins:
  - jekyll-paginate

# Custom vars
version:          1.0.0

github:
  url:            https://github.com/rymndhng

twitter:
  url:            https://twitter.com/rymndhng
